"""
mocha_script_exporter.py

Gera um script Python (template) para ser executado dentro do Mocha Pro.
Como a API do Mocha pode variar por versão/build, este exporter prioriza:
- estrutura clara
- pontos de extensão
- serialização simples dos blocos

Saída típica: mocha_import_script.py
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class MochaLayerSpec:
    name: str
    start_frame: int
    end_frame: int
    parameters: Dict[str, Any]


def build_mocha_python_script(
    layers: List[MochaLayerSpec],
    *,
    project_fps: Optional[float] = None,
    notes: Optional[str] = None,
) -> str:
    """
    Retorna um script Python como string.

    O script tenta criar uma estrutura (layers/tracks) dentro do Mocha.
    Ajuste as chamadas da API de acordo com seu Mocha Pro (2026).
    """
    header = [
        "# -*- coding: utf-8 -*-",
        "# Auto-generated by mocha_script_exporter.py",
        "",
        "'''",
        "Template de import para Mocha Pro.",
        "Ajuste as chamadas de API (mocha.project / mocha.clip / etc) conforme sua versão.",
        "'''",
        "",
    ]
    if notes:
        header += [f"# Notes: {notes}", ""]

    if project_fps is not None:
        header += [f"PROJECT_FPS = {float(project_fps)}", ""]
    else:
        header += ["PROJECT_FPS = None", ""]

    header += [
        "LAYER_SPECS = [",
    ]

    for l in layers:
        header.append(
            "  {"
            f"'name': {l.name!r}, "
            f"'start_frame': {int(l.start_frame)}, "
            f"'end_frame': {int(l.end_frame)}, "
            f"'parameters': {l.parameters!r}"
            "},"
        )

    header += [
        "]",
        "",
        "def _log(msg):",
        "    try:",
        "        print(msg)",
        "    except Exception:",
        "        pass",
        "",
        "def main():",
        "    _log('Importing layers into Mocha (template)...')",
        "    _log(f'Number of layers: {len(LAYER_SPECS)}')",
        "    # TODO: hook into Mocha API here",
        "    # Example pseudocode (adjust to Mocha's actual API):",
        "    # project = mocha.project()",
        "    # clip = project.clip(0)",
        "    # for spec in LAYER_SPECS:",
        "    #     layer = clip.createLayer(spec['name'])",
        "    #     layer.setInFrame(spec['start_frame'])",
        "    #     layer.setOutFrame(spec['end_frame'])",
        "    #     # set tracking parameters, link masks, etc.",
        "    #     # layer.tracker().setParameters(spec['parameters'])",
        "    #",
        "    _log('Done (template).')",
        "",
        "if __name__ == '__main__':",
        "    main()",
        "",
    ]

    return "\n".join(header)